### ISSUE TITLE
Runtime error when building in Android 2.0.0 Preview 5

### ISSUE THREAD

**Issue by calebsander** [ftctechnh/ftc_app#123]
When I build in Preview 5, running gives the following runtime error:
````
01-15 19:53:22.643 9074-9074/com.qualcomm.ftcrobotcontroller E/AndroidRuntime: FATAL EXCEPTION: main
 Process: com.qualcomm.ftcrobotcontroller, PID: 9074
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qualcomm.ftcrobotcontroller/com.qualcomm.ftcrobotcontroller.FtcRobotControllerActivity}: android.view.InflateException: Binary XML file line #49: Error inflating class android.widget.ImageView
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2187)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
     at android.app.ActivityThread.access$800(ActivityThread.java:138)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:136)
     at android.app.ActivityThread.main(ActivityThread.java:5095)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
     at dalvik.system.NativeStart.main(Native Method)
  Caused by: android.view.InflateException: Binary XML file line #49: Error inflating class android.widget.ImageView
     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290)
     at android.app.Activity.setContentView(Activity.java:1929)
     at com.qualcomm.ftcrobotcontroller.FtcRobotControllerActivity.onCreate(FtcRobotControllerActivity.java:142)
     at android.app.Activity.performCreate(Activity.java:5231)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236) 
     at android.app.ActivityThread.access$800(ActivityThread.java:138) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:136) 
     at android.app.ActivityThread.main(ActivityThread.java:5095) 
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:515) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
     at dalvik.system.NativeStart.main(Native Method) 
  Caused by: java.lang.reflect.InvocationTargetException
     at java.lang.reflect.Constructor.constructNative(Native Method)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     at android.view.LayoutInflater.createView(LayoutInflater.java:594)
     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669) 
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694) 
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
     at android.app.Activity.setContentView(Activity.java:1929) 
     at com.qualcomm.ftcrobotcontroller.FtcRobotControllerActivity.onCreate(FtcRobotControllerActivity.java:142) 
     at android.app.Activity.performCreate(Activity.java:5231) 
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151) 
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236) 
     at android.app.ActivityThread.access$800(ActivityThread.java:138) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:136) 
     at android.app.ActivityThread.main(ActivityThread.java:5095) 
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:515) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
     at dalvik.system.NativeStart.main(Native Method) 
  Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f020003 a=-1 r=0x7f020003}
     at android.content.res.Resources.loadDrawable(Resources.java:2068)
     at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
     at android.view.View.<init>(View.java:3554)
     at android.widget.ImageView.<init>(ImageView.java:123)
     at android.widget.ImageView.<init>(ImageView.java:119)
     at java.lang.reflect.Constructor.constructNative(Native Method) 
     at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
     at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
     at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56) 
     at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669) 
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694) 
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:290) 
     at android.app.Activity.setContentView(Activity.java:1929) 
     at com.qualcomm.ftcrobotcontroller.FtcRobotControllerActivity.onCreate(FtcRobotControllerActivity.java:142) 
     at android.app.Activity.performCreate(Activity.java:5231) 
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2151) 
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236) 
     at android.app.ActivityThread.access$800(ActivityThread.java:138) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:136) 
     at android.app.ActivityThread.main(ActivityThread.java:5095) 
     at java.lang.reflect.Method.invokeNative(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:515) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
     at dalvik.system.NativeStart.main(Native Method) 
````
I also had to make some modifications to `build.grade` in order to get it to run, so it is possible that those have something to do with it:
````
apply plugin: 'com.android.application'

android {
    compileSdkVersion = 19
    buildToolsVersion = '19.1'
    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 19
    }
}

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0-alpha5'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

allprojects {
    repositories {
        jcenter()
        flatDir {
            dirs 'out'
        }
    }
}

dependencies {
    compile files('libs/android-support-v4.jar')
    compile(name: 'RobotCore-release', ext: 'aar')
    compile(name: 'Hardware-release', ext: 'aar')
    compile(name: 'FtcCommon-release', ext: 'aar')
    compile(name: 'ModernRobotics-release', ext: 'aar')
    compile(name: 'Analytics-release', ext: 'aar')
    compile(name: 'WirelessP2p-release', ext: 'aar')
}
````

**Comment by calebsander** [comment]
Seems fixed in the newest release.
