### ISSUE TITLE
REV Expansion Hub unresponsive on 3.1

### ISSUE THREAD

**Issue by nitrocalcite** [ftctechnh/ftc_app#367]
Occasionally, the RC will no longer recognize the REV module in practice.  In theory, it still claims that it is connected to the module (ie it does not show a disconnect warning).  However, it starts spamming assert exceptions which means that even the most basic opmode loop takes 2.5s to complete.  This can generally be fixed by restarting the RC and DS apps, but it will reoccur in the future.

Here is an excerpt of the first exception.  A full log can be found [here](https://gist.github.com/nitrocalcite/90a7f1a39a4fe0ee9a64ea3a37149b1d)  
```
08-31 18:31:53.272 11644-14370/com.qualcomm.ftcrobotcontroller V/RobotCore: thread: 'LinearOpMode main' starting...
08-31 18:31:53.302 11644-11726/com.qualcomm.ftcrobotcontroller V/Robocol: sending CMD_INIT_OP_MODE_RESP(7586), attempt: 0
08-31 18:31:53.522 11644-14370/com.qualcomm.ftcrobotcontroller V/RobotCore: timeout: abandoning waiting 250ms for response: cmd=LynxGetMotorChannelModeCommand mod=2 msg#=0
08-31 18:31:53.522 11644-14370/com.qualcomm.ftcrobotcontroller V/RobotCore: nack rec'd mod=2 msg#=0 ref#=0 reason=ABANDONED_WAITING_FOR_RESPONSE:256
08-31 18:31:53.522 11644-14370/com.qualcomm.ftcrobotcontroller A/RobotCore: assertion failed: 0x42638e50 on 0x428df388: closed
08-31 18:31:53.522 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore: java.lang.RuntimeException: assertion failed: 0x42638e50 on 0x428df388: closed
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at org.firstinspires.ftc.robotcore.internal.Assert.assertFailed(Assert.java:131)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at org.firstinspires.ftc.robotcore.internal.Assert.assertTrue(Assert.java:84)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.hardware.lynx.LynxUsbDeviceDelegate.assertOpen(LynxUsbDeviceDelegate.java:101)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.hardware.lynx.LynxUsbDeviceDelegate.getSerialNumber(LynxUsbDeviceDelegate.java:245)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.hardware.lynx.LynxModule.getSerialNumber(LynxModule.java:560)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.hardware.lynx.LynxController$PretendLynxModule.getSerialNumber(LynxController.java:370)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.hardware.lynx.LynxNackException.<init>(LynxNackException.java:58)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.hardware.lynx.commands.LynxRespondable.responseOrThrow(LynxRespondable.java:308)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.hardware.lynx.commands.LynxRespondable.sendReceive(LynxRespondable.java:248)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.hardware.lynx.LynxDcMotorController.internalGetMotorChannelMode(LynxDcMotorController.java:414)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.hardware.lynx.LynxDcMotorController.internalSetZeroPowerBehavior(LynxDcMotorController.java:465)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.hardware.lynx.LynxDcMotorController.setMotorZeroPowerBehavior(LynxDcMotorController.java:602)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.robotcore.hardware.DcMotorImpl.setZeroPowerBehavior(DcMotorImpl.java:233)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at org.firstinspires.ftc.teamcode.extensions.DbzMotor.setZeroPowerBehavior(DbzMotor.java:351)
08-31 18:31:53.542 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at org.firstinspires.ftc.teamcode.extensions.DbzMotor.init(DbzMotor.java:45)
08-31 18:31:53.552 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at org.firstinspires.ftc.teamcode.extensions.DbzOpMode.runOpMode(DbzOpMode.java:43)
08-31 18:31:53.552 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.robotcore.eventloop.opmode.LinearOpMode$LinearOpModeHelper$1.run(LinearOpMode.java:304)
08-31 18:31:53.552 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.robotcore.util.ThreadPool.logThreadLifeCycle(ThreadPool.java:702)
08-31 18:31:53.552 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.robotcore.eventloop.opmode.LinearOpMode$LinearOpModeHelper.run(LinearOpMode.java:299)
08-31 18:31:53.552 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-31 18:31:53.552 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-31 18:31:53.552 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at com.qualcomm.robotcore.util.ThreadPool$ThreadFactoryImpl$1.run(ThreadPool.java:757)
08-31 18:31:53.552 11644-14370/com.qualcomm.ftcrobotcontroller E/RobotCore:     at java.lang.Thread.run(Thread.java:841)
```

**Comment by nitrocalcite** [comment]
Closing since this issue magically disappeared with time, and have not seen this so far on 3.4
