### ISSUE TITLE
Accessing video stream from UVC camera w/o going through Vuforia

### ISSUE THREAD

**Issue by FROGbots-4634** [ftctechnh/ftc_app#593]
In SDK v4.0, as far as I know, it is not possible to access the video stream from a UVC camera without going through Vuforia.

For the next point release, would it be possible to enable access outside of Vuforia?

**Comment by rgatkinson** [comment]
It's possible in the current build, just not well/at all explained (a sample is in the works). 

If you're up for some digging, and wanted to plunge in right now (pardon the mixed metaphors), the place to start looking for inspiration about how to structure your code is in ``VuforiaWebcam``: ``openCamera()``, ``startCamera()``, ``stopCamera()``, and ``closeCamera()``.

**Comment by FROGbots-4634** [comment]
I had actually already done some digging; I saw that `VuforiaWebcam` was calling all kinds of C++ methods inside `libRobotCore.so` such as `nativeDeliverFrameToVuforiaUvc()` which (I thought) implied that the code was specifically crafted to work with Vuforia, and wasn't meant to be used separately.

But I guess that's a false assumption based on your comments, so I guess I'll take another look at it.

**Comment by rgatkinson** [comment]
Interacting with the corresponding native code is indeed what VuforiaWebcam does. However, the methods I pointed to are the ones therein that do the manipulation of the camera (whose frames are then passed down to native code, once streaming starts). Making analogies of what those are doing is what you're looking for.

**Comment by FROGbots-4634** [comment]
Gotcha. I also just now discovered `WebcamExample.java`, and that should help too :)

**Comment by FROGbots-4634** [comment]
Hmm, so both `WebcamExample.java` and my stripped-down version of `VuforiaWebcam.java` crash with:
```

java.lang.IllegalArgumentException: pointer must not be null
at org.firstinspires.ftc.robotcore.internal.system.NativeObject.<init>(NativeObject.java:82)
at org.firstinspires.ftc.robotcore.internal.system.NativeObject.<init>(NativeObject.java:73)
at org.firstinspires.ftc.robotcore.internal.system.NativeObject.<init>(NativeObject.java:90)
at org.firstinspires.ftc.robotcore.internal.camera.libuvc.nativeobject.UvcDeviceInfo.<init>(UvcDeviceInfo.java:52)
at org.firstinspires.ftc.robotcore.internal.camera.libuvc.nativeobject.UvcDevice.getDeviceInfo(UvcDevice.java:249)
at org.firstinspires.ftc.robotcore.internal.camera.libuvc.nativeobject.UvcDevice.getStreamingInterfaces(UvcDevice.java:254)
at org.firstinspires.ftc.robotcore.internal.camera.names.WebcamNameImpl.getCameraCharacteristics(WebcamNameImpl.java:341)
at org.firstinspires.ftc.robotcore.internal.camera.WebcamExample$OneCameraExample$2.accept(WebcamExample.java:167)
at org.firstinspires.ftc.robotcore.internal.camera.WebcamExample$OneCameraExample$2.accept(WebcamExample.java:161)
at org.firstinspires.ftc.robotcore.internal.camera.names.WebcamNameImpl$3$1.handle(WebcamNameImpl.java:296)
at org.firstinspires.ftc.robotcore.internal.camera.names.WebcamNameImpl$3$1.handle(WebcamNameImpl.java:293)
at org.firstinspires.ftc.robotcore.external.function.Continuation.dispatchHere(Continuation.java:241)
at org.firstinspires.ftc.robotcore.internal.camera.names.WebcamNameImpl$3.accept(WebcamNameImpl.java:292)
at org.firstinspires.ftc.robotcore.internal.camera.names.WebcamNameImpl$3.accept(WebcamNameImpl.java:287)
at org.firstinspires.ftc.robotcore.internal.system.AppUtil$8.handle(AppUtil.java:961)
at org.firstinspires.ftc.robotcore.internal.system.AppUtil$8.handle(AppUtil.java:958)
at org.firstinspires.ftc.robotcore.external.function.Continuation$ExecutorDispatcher$1.run(Continuation.java:151)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at com.qualcomm.robotcore.util.ThreadPool$ThreadFactoryImpl$1.run(ThreadPool.java:793)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by FROGbots-4634** [comment]
Hmm, OK I think I fixed that error, but no matter what resolution I choose, I can't get it to stream at more than 15FPS....

**Comment by FROGbots-4634** [comment]
Ok so actually the one adapted from VuforiaWebcam runs at 15, but the one adapted from WebcamExample runs at 30...

**Comment by FROGbots-4634** [comment]
I also found this in `/data/tombstones`: https://gist.github.com/FROGbots-4634/38b928ab259a114185aebd40178c143f

It mentions `libRobotCore.so` so I think it's probably related
